language: python
dist: bionic   # required for Python >= 3.7
cache: pip

# Environment changes have to be manually synced with 'tox.ini'.
# See: https://github.com/travis-ci/travis-ci/issues/3024

python:
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - python: 3.5
      dist: xenial  # Bionic has no Python 3.5

    # Disabled, see https://github.com/sybrenstuvel/python-rsa/issues/131
    #- python: pypy3.5
    #  dist: xenial  # Bionic has no Python 3.5

install:
  - pip install poetry
  - poetry install -v

script:
  - poetry run py.test tests/

after_success:
  - poetry run coveralls
